services:
    ajax_satisfaction.form.personSatisfaction:
        class: Ajax\SatisfactionBundle\Form\PersonSatisfactionType
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: form.type, alias: satisfaction_form }